Repository AJD-Archive/Kkeujeok_Frontend, pull requests merged in 2024-09, with the labels that each got.

#29 개인 대시보드 확인 api 연결 & 사이드 페이지 api 연결
  package.json
  src/App.tsx
  src/api/BoardApi.tsx
  src/api/PersonalBlockApi.ts
  src/components/Block.tsx
  src/components/CompletedDashboard.tsx
  src/components/Dashboard.tsx
  src/components/InProgressDashboard.tsx
  src/components/NotStartedDashboard.tsx
  src/contexts/OAuthRedirectHandler.tsx
  src/hooks/useSidePage.ts
  src/pages/MainPage.tsx
  src/pages/SidePage.tsx
  src/styles/DashboardStyled.tsx
  src/styles/SidePageStyled.tsx
  src/types/Columns.ts
  src/types/PersonalBlock.ts
  src/types/PersonalDashBoard.tsx
  yarn.lock
Labels: 💡 feature, 🛠️ fix, 💬 chore

#33 기본 대시 보드 페이지 경로 수정
  src/App.tsx
  src/components/Dashboard.tsx
  src/utils/apiConfig.tsx
Labels: 📑 docs

#35 개인 대시보드 확인 및 수정
  src/App.tsx
  src/api/BoardApi.tsx
  src/components/Dashboard.tsx
  src/components/Graph.tsx
  src/components/Header.tsx
  src/contexts/DashboardAtom.ts
  src/hooks/usePersonalDashBoard.tsx
  src/pages/CreatePersonalBoardPage.tsx
  src/pages/MainPage.tsx
  src/pages/TeamDocument.tsx
  src/pages/TeamFileBoard.tsx
  src/styles/DashboardStyled.tsx
  src/types/PersonalDashBoard.tsx
Labels: 💡 feature, 💅🏻 style

#38 [#36] 로그인 페이지 디자인 수정 & 로딩창 추가
  package.json
  src/App.tsx
  src/components/Loading.tsx
  src/contexts/OAuthRedirectHandler.tsx
  src/pages/LoginPage.tsx
  src/styles/LoadingStyled.tsx
  src/styles/LoginPageStyled.tsx
  yarn.lock
Labels: 💡 feature, 💅🏻 style, 💬 chore

#40 [#39] 팀 대시보드 생성 및 수정
  src/App.tsx
  src/api/TeamDashBoardApi.tsx
  src/pages/CreateTeamBoardPage.tsx
  src/types/TeamDashBoard.ts
Labels: 💡 feature

#43 navbar 개인 대시보드에 카테고리 분류 적용
  src/components/Dashboard.tsx
  src/components/Navbar.tsx
  src/styles/DashboardStyled.tsx
  src/styles/NavBarStyled.tsx
Labels: 💡 feature, 💅🏻 style

#52 팀 문서 api 연결
  src/api/TeamDocumentApi.ts
  src/components/DocumentCard.tsx
  src/components/Header.tsx
  src/hooks/useTeamDocument.ts
  src/pages/TeamDocument.tsx
  src/pages/TeamDocumentBoard.tsx
  src/styles/TeamDocumentStyled.tsx
  src/types/TeamDocumentType.ts
Labels: 💡 feature

#41 #25 feat: 개인 대시보드 휴지통 css
  src/api/BoardApi.tsx
  src/api/PersonalBlockApi.ts
  src/components/Block.tsx
  src/components/DeleteButton.tsx
  src/components/Header.tsx
  src/components/NotStartedDashboard.tsx
  src/contexts/atoms.ts
  src/pages/MainPage.tsx
  src/styles/DashboardStyled.tsx
  src/styles/MainPageStyled.tsx
  src/utils/columnsConfig.ts
  yarn.lock
Labels: 💅🏻 style

#60 팀 대시보드 팀원 초대 및 탈퇴
  src/api/BoardApi.tsx
  src/components/Header.tsx
  src/img/userDefault.png
  src/pages/CreateTeamBoardPage.tsx
  src/styles/CreateBoardPageStyled.tsx
  src/types/TeamDashBoard.ts
Labels: 💡 feature, 🛠️ fix, 💻 refactor

#70 챌린지 생성 오류 수정
  src/pages/CreateChallengePage.tsx
Labels: 🛠️ fix
